const seedCars = [
  {
    id: 'car-101',
    title: 'Toyota Innova Crysta 2.4 ZX Diesel',
    brand: 'Toyota',
    model: 'Innova Crysta',
    year: 2023,
    price: 1850000,
    originalPrice: 1900000,
    priceDrop: true,
    rentalPricePerDay: 3500,
    sellerExpectedPrice: 1750000,
    purchasePriceByAdmin: 1780000,
    kmDriven: 18500,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    color: 'Super White',
    bodyType: 'MUV',
    location: 'Chennai',
    distanceKm: 8,
    vin: 'MBJ11234567890IN',
    licensePlate: 'TN 09 CB 8899',
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800'
    ],
    description: 'Certified 140+ point inspected Toyota Innova Crysta ZX top model. Full service history at authorized Toyota center, leather seating, captain seats, single owner.',
    status: 'sale_and_rent',
    targetMarket: 'both',
    sellerId: 'seller1',
    sellerName: 'Ramesh Kumar',
    aiInspection: {
      damageScore: 97,
      blurPassed: true,
      ocrPlateDetected: 'TN 09 CB 8899',
      detectedColor: 'Pearl White',
      estimatedMarketValue: 1820000,
      damagePoints: [{ x: 40, y: 50, label: 'Micro Scratch bumper', severity: 'low' }]
    },
    features: ['Captain Seats', 'Touchscreen Infotainment', 'Cruise Control', '7 Airbags', 'Rear AC Vents', 'Reverse Camera'],
    rating: 4.9
  },
  {
    id: 'car-102',
    title: 'Hyundai Creta SX 1.5 Petrol',
    brand: 'Hyundai',
    model: 'Creta',
    year: 2022,
    price: 920000,
    originalPrice: 970000,
    priceDrop: true,
    rentalPricePerDay: 2200,
    sellerExpectedPrice: 870000,
    purchasePriceByAdmin: 890000,
    kmDriven: 24000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    color: 'Titan Grey',
    bodyType: 'SUV',
    location: 'Chennai',
    distanceKm: 14,
    vin: 'MAL22987654321HY',
    licensePlate: 'TN 07 AX 1234',
    images: [
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800',
      'https://images.unsplash.com/photo-1541348263662-e082662d82da?w=800'
    ],
    description: 'Pristine condition Creta SX with panoramic sunroof, wireless charging, and ambient lighting. Fully verified by CarHub Admin team.',
    status: 'sale_and_rent',
    targetMarket: 'both',
    sellerId: 'seller2',
    sellerName: 'Anita Sharma',
    aiInspection: {
      damageScore: 94,
      blurPassed: true,
      ocrPlateDetected: 'TN 07 AX 1234',
      detectedColor: 'Titan Grey',
      estimatedMarketValue: 910000,
      damagePoints: []
    },
    features: ['Sunroof', 'Bose Sound System', 'Wireless Charging', 'LED DRLs', 'Keyless Entry'],
    rating: 4.8
  },
  {
    id: 'car-103',
    title: 'Kia Sonet GTX Plus 1.5 Diesel',
    brand: 'Kia',
    model: 'Sonet',
    year: 2023,
    price: 790000,
    originalPrice: 820000,
    priceDrop: false,
    rentalPricePerDay: 1800,
    sellerExpectedPrice: 750000,
    purchasePriceByAdmin: 765000,
    kmDriven: 16000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    color: 'Intense Red',
    bodyType: 'SUV',
    location: 'Chennai',
    distanceKm: 5,
    vin: 'KNA3345678901KI',
    licensePlate: 'TN 22 DK 5566',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800'
    ],
    description: 'Compact sporty SUV with red accents, ventilated seats, 10.25 inch screen, and Bose 7 speaker system.',
    status: 'for_sale',
    targetMarket: 'buyer',
    sellerId: 'seller3',
    sellerName: 'Vikram Singh',
    aiInspection: {
      damageScore: 96,
      blurPassed: true,
      ocrPlateDetected: 'TN 22 DK 5566',
      detectedColor: 'Intense Red',
      estimatedMarketValue: 785000,
      damagePoints: []
    },
    features: ['Ventilated Seats', 'Bose Audio', 'Subwoofer', 'Drive Modes', 'Tire Pressure Monitor'],
    rating: 4.7
  },
  {
    id: 'car-104',
    title: 'Mahindra Thar LX Hard Top Diesel 4x4',
    brand: 'Mahindra',
    model: 'Thar',
    year: 2023,
    price: 1450000,
    originalPrice: 1500000,
    priceDrop: true,
    rentalPricePerDay: 3800,
    sellerExpectedPrice: 1380000,
    purchasePriceByAdmin: 1400000,
    kmDriven: 12000,
    fuelType: 'Diesel',
    transmission: 'Manual',
    color: 'Napoli Black',
    bodyType: 'SUV',
    location: 'Chennai',
    distanceKm: 19,
    vin: 'MA1449871234MH',
    licensePlate: 'TN 10 EF 9000',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800'
    ],
    description: 'Iconic 4x4 off-roader with hardtop convertibility, touchscreen navigation, and roll cage structure.',
    status: 'for_rent',
    targetMarket: 'renter',
    sellerId: 'seller4',
    sellerName: 'Karthik Raja',
    aiInspection: {
      damageScore: 92,
      blurPassed: true,
      ocrPlateDetected: 'TN 10 EF 9000',
      detectedColor: 'Napoli Black',
      estimatedMarketValue: 1420000,
      damagePoints: []
    },
    features: ['4x4 Low Range', 'Touchscreen', 'Roll Cage', 'Water Resistant Interior'],
    rating: 4.9
  },
  {
    id: 'car-105',
    title: 'BMW 3 Series 320d Luxury Line',
    brand: 'BMW',
    model: '3 Series',
    year: 2021,
    price: 3150000,
    originalPrice: 3300000,
    priceDrop: true,
    rentalPricePerDay: 6500,
    sellerExpectedPrice: 2950000,
    purchasePriceByAdmin: 3000000,
    kmDriven: 28000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    color: 'Phytonic Blue',
    bodyType: 'Sedan',
    location: 'Chennai',
    distanceKm: 22,
    vin: 'WBA5566778899BMW',
    licensePlate: 'TN 01 ZZZ 007',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800'
    ],
    description: 'Executive luxury sedan with BMW Live Cockpit Professional, Harman Kardon sound, and sunroof.',
    status: 'sale_and_rent',
    targetMarket: 'both',
    sellerId: 'seller5',
    sellerName: 'Suresh Raina',
    aiInspection: {
      damageScore: 98,
      blurPassed: true,
      ocrPlateDetected: 'TN 01 ZZZ 007',
      detectedColor: 'Phytonic Blue',
      estimatedMarketValue: 3100000,
      damagePoints: []
    },
    features: ['Harman Kardon', 'Gesture Control', 'Memory Seats', 'Parking Assistant', 'Ambient Light'],
    rating: 5.0
  },
  {
    id: 'car-106',
    title: 'Tata Safari XZA+ Dark Edition 2023',
    brand: 'Tata',
    model: 'Safari',
    year: 2023,
    sellerExpectedPrice: 1950000,
    engineCapacity: '2.0L Kryotec Turbo Diesel',
    kmDriven: 14200,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    color: 'Oberon Black',
    bodyType: 'SUV',
    noOfOwners: '1st Owner',
    location: 'Anna Nagar, Chennai',
    address: '2nd Avenue, Anna Nagar West',
    distanceKm: 5,
    vin: 'MAT6677889900TA',
    licensePlate: 'TN 02 BB 4455',
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800',
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800'
    ],
    description: 'Single owner dark edition Safari with panoramic sunroof, JBL 9 speaker audio, ventilated 1st and 2nd row captain seats.',
    status: 'seller_posted',
    targetMarket: 'buyer',
    sellerId: 'usr-seller',
    sellerName: 'Suresh Sakthivel',
    ownerName: 'Suresh Sakthivel',
    additionalInfo: {
      abs: 'Yes',
      adjustableSteering: 'Yes',
      alloyWheels: 'Yes',
      antiTheftDevice: 'Yes',
      auxCompatibility: 'Yes',
      bluetooth: 'Yes',
      color: 'Dark Black',
      cruiseControl: 'Yes',
      insuranceType: 'Comprehensive Zero Dep',
      makeMonth: 'June',
      navigationSystem: 'Yes',
      parkingSensors: 'Yes',
      powerSteering: 'Yes',
      amFmRadio: 'Yes',
      rearParkingCamera: 'Yes',
      registrationPlace: 'TN',
      exchange: 'Yes',
      finance: 'Yes',
      sunroof: 'Yes',
      usbCompatibility: 'Yes'
    },
    features: ['Ventilated Captain Seats', 'JBL Audio', 'Panoramic Sunroof', 'ADAS Level 2', '360 Camera']
  },
  {
    id: 'car-107',
    title: 'Maruti Suzuki Grand Vitara Alpha Hybrid 2023',
    brand: 'Maruti Suzuki',
    model: 'Grand Vitara',
    year: 2023,
    sellerExpectedPrice: 1520000,
    engineCapacity: '1.5L Intelligent Electric Hybrid',
    kmDriven: 11500,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    color: 'Nexa Blue',
    bodyType: 'SUV',
    noOfOwners: '1st Owner',
    location: 'Guindy, Chennai',
    address: 'GST Road, Guindy Industrial Estate',
    distanceKm: 4,
    vin: 'MSIL7788990011GV',
    licensePlate: 'TN 09 AZ 9988',
    images: [
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800',
      'https://images.unsplash.com/photo-1541348263662-e082662d82da?w=800',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800'
    ],
    description: 'Strong hybrid electric SUV with 27.97 kmpl fuel efficiency, HUD display, and EV drive mode.',
    status: 'seller_posted',
    targetMarket: 'buyer',
    sellerId: 'usr-seller-2',
    sellerName: 'Karthik Raman',
    ownerName: 'Karthik Raman',
    additionalInfo: {
      abs: 'Yes',
      adjustableSteering: 'Yes',
      alloyWheels: 'Yes',
      antiTheftDevice: 'Yes',
      auxCompatibility: 'Yes',
      bluetooth: 'Yes',
      color: 'Nexa Blue',
      cruiseControl: 'Yes',
      insuranceType: 'Comprehensive',
      makeMonth: 'August',
      navigationSystem: 'Yes',
      parkingSensors: 'Yes',
      powerSteering: 'Yes',
      amFmRadio: 'Yes',
      rearParkingCamera: 'Yes',
      registrationPlace: 'TN',
      exchange: 'Yes',
      finance: 'Yes',
      sunroof: 'Yes',
      usbCompatibility: 'Yes'
    },
    features: ['EV Drive Mode', 'Heads Up Display', 'Wireless Apple CarPlay', 'Panoramic Sunroof']
  }
];

module.exports = seedCars;
